package

diff --git a/dists/jetty-deb/src/main/unix/scripts/postinst b/dists/jetty-deb/src/main/unix/scripts/postinst
--- a/dists/jetty-deb/src/main/unix/scripts/postinst
+++ b/dists/jetty-deb/src/main/unix/scripts/postinst
@@ -1,20 +1,72 @@
-#!/bin/bash
+#!/bin/sh
+# postinst script for jetty9
+#
+# see: dh_installdeb(1)
 
-LOG_DIR=/var/lib/jetty9/logs
-WEBAPP_DIR=/var/lib/jetty9/webapps
+set -e
 
-# copy the jetty start script into place
-cp /usr/share/jetty9/bin/jetty.sh /etc/init.d/jetty
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# make it generally executable
-chmod 755 /etc/init.d/jetty
 
-# ensure we have a logging directory
-if [ ! -d "$LOG_DIR" ]; then
-  mkdir $LOG_DIR
-fi
+case "$1" in
+    configure)
+		LOG_DIR=/var/log/jetty
+		WEBAPP_DIR=/var/lib/jetty/webapps
+		CACHE_DIR=/var/cache/jetty/tmp
 
-# ensure we have a webapps directory
-if [ ! -d "$WEBAPP_DIR" ]; then
-  mkdir $WEBAPP_DIR
-fi
+		# copy the jetty start script into place
+
+		cp /usr/share/jetty/bin/jetty.sh /etc/init.d/jetty
+
+		# make it generally executable
+		chmod 755 /etc/init.d/jetty
+
+		# ensure we have a logging directory
+		if [ ! -d "$LOG_DIR" ]; then
+		  mkdir -p $LOG_DIR
+		fi
+
+		# ensure we have a webapps directory
+		if [ ! -d "$WEBAPP_DIR" ]; then
+		  mkdir -p $WEBAPP_DIR
+		fi
+
+		if [ ! -d "$CACHE_DIR" ]; then
+		  mkdir -p $CACHE_DIR
+		fi
+
+		if [ ! -f /etc/jetty/start.ini ]; then
+                  cp /usr/share/jetty/start.ini /etc/jetty/start.ini
+		fi
+
+		if [ ! -L /usr/share/jetty/etc ]; then
+			ln -s /etc/jetty /usr/share/jetty/etc
+		fi
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
